spring:
  security:
    user:
      name: ${APIUSER:admin}
      password: ${APIPWD:1}

  redis:
    host: ${RedisHost:redis}
    port: 6379
    database: 1
    password:
  # JavaMailSender 邮件发送的配置
  mail:
    host: smtp.139.com
    username: xx@139.com
    password: xx
    test-connection: false
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactor
music-api: ${MusicApi:http://jusicMusicApi}
jusic:
  music-expire-time: ${MusicExpireTime:1200000}
  retry-count: ${ReTryCount:2}
  vote-rate: ${VoteRate:0.3}
  default-music-file: 'classpath:music/default-list.txt'#'file:/usr/local/nginx/html/default-list.txt' # ## #
  wy-top-url: ${WyTopUrl:3778678}
  music-json: 'https://alang-srt.oss-cn-beijing.aliyuncs.com/lizhimusic.json'#'classpath:lizhimusic.json'#'file:/usr/local/nginx/html/lizhimusic.json'##json格式歌曲列表（for禁歌） # #
  ai-url: 'https://studio-api.suno.ai/api/trending/metaplaylist'
  music-serve-domain: ${music-api}:3000 #'http://www.alang.run:8888'
  music-serve-domain-qq: ${music-api}:3300 #'http://www.alang.run:3300'
  music-serve-domain-mg: ${music-api}:3400 #'http://www.alang.run:3400'#
  music-serve-domain-kw-xm: ${music-api}:8081 #'http://www.alang.run:8081'#'
  mail-send-from: ${MailFrom:xxx@139.com}
  mail-send-to: ${MailTo:1040927107@qq.com}
  serverJUrl: ${ServerJUrl:https://sc.ftqq.com/SCU64668T909ada7955daadfb64d5e7652b93fb135dad06e659369.send}
  ip_house: ${IpHouse:128}
  house_size: ${HouseSize:128}
  mini_id: ${MiniId:wx693312f83f255cf3}
  mini_secrect: ${MiniSecrect:xx}
  role_root_password: ${RoleRootPassword:xx}
  wy_account: ${WyAccount:a01lang@163.com}
  wy_password: ${WyPassword:xxx}
  playlist_size: ${PlaylistSize:23}
  foreverlist_size: ${$ForeverlistSize:128}
  qq_uin: ${QqUin:1040927107}
  qq_music_key: ${QqMusicKey:Q_H_L_63k3NWYfBRq1KV0rBZ4ySa7vYK6XS5803Q23v35s4abc0rela9BzP6jBXv5Fgk9hsk4FLXXXXXX} #qq音乐cookie找到qqMusicKey,需要会员
  qq_music_guid: ${QqMusicGuid:114514}
  qq_cdn_addr: ${QqCdnAddr:http://ws.stream.qqmusic.qq.com/}
  qq_refresh_interval: ${QqRefreshInterval:86000000} #毫秒